### PR TITLE
Disable hardtime on popups

### PR DESCRIPTION
**Pull request by lstephen**
Address #53

### CODE REVIEW

**Comment by andrewferrier** [comment]
Thanks for this. I was one of the people watching https://github.com/takac/vim-hardtime/issues/53. Unfortunately, this doesn't quite address my issue at least. I want to encourage myself to just use `h, j, k, l`, and so I put the arrow keys into `g:list_of_disabled_keys`. However, when you're in the completion pop-up menu, `h, j, k, l` don't scroll - instead they insert those literal characters (which makes sense). So I want to allow the arrow keys, but only in the popup menu. It seems like the change you made doesn't allow for that combination - is that right?

**Comment by lstephen** [comment]
Yes, you are correct. Disabled keys will still be disabled with the way I have made the change here.

To allow h,j,k,l to scroll in the popup, they would have to be remapped. i.e., it's not vim-hardtime that is preventing you from using j,k to scroll in the popup, they don't work in a standard vim config.

With arrow keys disabled, you should still be able to use <C-n> and <C-p> to scroll the popup. Or, you could remap j/k to scroll in the pop and vim-hardtime should not prevent that (https://stackoverflow.com/questions/4739901/scrolling-in-vim-autocomplete-box-with-jk-movement-keys)

**Comment by lstephen** [comment]
Oh, I think i misunderstood. When the popup is visible, you want it to behave as if hardtime was off completely?

**Comment by lstephen** [comment]
@andrewferrier I have updated this so that disabled keys are enabled when a popup is visible (i.e., when a popup is visible things should behave as if hardtime is off)

**Comment by scrouthtv** [comment]
Is this going to be merged some time soon @takac ?

**Comment by takac** [comment]
@scrouthtv have you tested this patch?

**Comment by scrouthtv** [comment]
Yes, it works for me.

**Pull request merged**
